showNotBar: true
barBody: "Announcement: Fingerprint Triples Revenue and Users, Crosses One
  Billion Monthly API Calls"
arrowText: Read more
url: https://fingerprint.com/blog/fy23-momentum-press-release
openUrlNewTab: false
backgroundColor: "#f04405"
