export const GATSBY_FPJS_TOKEN = process.env.GATSBY_FPJS_TOKEN
export const GATSBY_FPJS_API_TOKEN = process.env.GATSBY_FPJS_API_TOKEN
export const GATSBY_FPJS_ENDPOINT = process.env.GATSBY_FPJS_ENDPOINT
export const GATSBY_FPJS_REGION = process.env.GATSBY_FPJS_REGION
export const GATSBY_FPJS_DASHBOARD_ENDPOINT = process.env.GATSBY_FPJS_DASHBOARD_ENDPOINT
export const GATSBY_GITHUB_API_TOKEN = process.env.GATSBY_GITHUB_API_TOKEN
export const GATSBY_ROLLBAR_ACCESS_TOKEN = process.env.GATSBY_ROLLBAR_ACCESS_TOKEN
